// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvo8iZmpyzvCmwoTPiROPsScWVB5I6M3g',
    appId: '1:512999585882:android:bb4625d55a5b7004c2c063',
    messagingSenderId: '512999585882',
    projectId: 'chargeiq-lithi',
    storageBucket: 'chargeiq-lithi.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbhC4mHv4bkW0VeLYv_nRRovdV4SZ0dLU',
    appId: '1:512999585882:web:e292e895833511c1c2c063',
    messagingSenderId: '512999585882',
    projectId: 'chargeiq-lithi',
    authDomain: 'chargeiq-lithi.firebaseapp.com',
    storageBucket: 'chargeiq-lithi.firebasestorage.app',
    measurementId: 'G-3XD9BQ7K5V',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjL9QdgZLiZU6zGv311TIeFuvZOvv-ORA',
    appId: '1:512999585882:ios:b8a71b0420a27a5ec2c063',
    messagingSenderId: '512999585882',
    projectId: 'chargeiq-lithi',
    storageBucket: 'chargeiq-lithi.firebasestorage.app',
    iosClientId: '512999585882-fo9da872pgtp2odff5j58clpa74t70qj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chargeIqApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjL9QdgZLiZU6zGv311TIeFuvZOvv-ORA',
    appId: '1:512999585882:ios:b8a71b0420a27a5ec2c063',
    messagingSenderId: '512999585882',
    projectId: 'chargeiq-lithi',
    storageBucket: 'chargeiq-lithi.firebasestorage.app',
    iosClientId: '512999585882-fo9da872pgtp2odff5j58clpa74t70qj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chargeIqApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbhC4mHv4bkW0VeLYv_nRRovdV4SZ0dLU',
    appId: '1:512999585882:web:62004ca991d092f7c2c063',
    messagingSenderId: '512999585882',
    projectId: 'chargeiq-lithi',
    authDomain: 'chargeiq-lithi.firebaseapp.com',
    storageBucket: 'chargeiq-lithi.firebasestorage.app',
    measurementId: 'G-X84F4Z1JQC',
  );
}
